<a href="https://colab.research.google.com/github/Nandhinidura/python/blob/main/Basics_of_numpy_by_nethaji.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
n = np.array([1,2,3,4])
dd = np.array([[1,2,3,4],[1,2,3,4]])
dd

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.random.random(10)

array([0.9605276 , 0.90837926, 0.33104265, 0.85030974, 0.1638547 ,
       0.41051284, 0.96365991, 0.60717958, 0.81771711, 0.86699815])

In [ ]:
np.random.random((3,2))

array([[0.97284313, 0.80508246],
       [0.76884287, 0.3808334 ],
       [0.09582346, 0.88300733]])

In [ ]:
a = np.random.random((3,2))
a

array([[0.63515376, 0.35498567],
       [0.48011063, 0.60050327],
       [0.67840496, 0.52507066]])

In [ ]:
#nandhu saved in google drive let's check nandhu.npy
np.save("nandhu",a)

In [ ]:
b = np.load("/content/nandhu.npy")
b

array([[0.63515376, 0.35498567],
       [0.48011063, 0.60050327],
       [0.67840496, 0.52507066]])

In [ ]:
#n.txt saved in the google drive let's check.....
np.savetxt("n.txt",a)

In [ ]:
a =[1,2,3]
b =[2,3,4]
print(np.add(a,b))

[3 5 7]


In [ ]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


In [ ]:
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [ ]:
print(np.log(10))

2.302585092994046


In [ ]:
n.sum()

10

In [ ]:
np.sum(a)

6

Folder Handling


In [ ]:
#list what we are have the file actually.....
!ls

nandhu.npy  n.txt  sample_data


In [ ]:
#!which dirctory am working now for that am using pwd-->present working directory...
!pwd

/content


In [ ]:
#mkdir is used to make directory give the krishna folder to my google drive......
!mkdir krishna

In [ ]:
#if i want to remove remove folder from the google drive you can use !rmdir
!rmdir krishna

In [ ]:
#creating directory to my google drive but above are the linux command in this python file folder making....
import os
os.mkdir("datascience")

In [ ]:
#renaming directionary
os.rename("datascience","dw4")

In [ ]:
#removing directionary
os.rmdir("dw4")

In [ ]:
#File Handling
#create,modify-->read and write mode,delete
#x-->Admin access the user print whatever you want
#"x" - Create - will create a file, returns an error if the file exist
 
file1= open("nirmal1.py", "x")
 
#"w" - Write - will create a file if the specified file does not exist
 
file1 = open("guvi1.txt", "w")


In [ ]:
#Write to an Existing File
#To write to an existing file, you must add a parameter to the open() function:
 
#"a" - Append - will append to the end of the file
 
#"w" - Write - will overwrite any existing content
 
file1 = open("guvi.txt", "w")
file1.write("aaaaaaaaaaaaaaa")
file1.close()
#You should always close your files, in some cases, due to buffering, changes made to a file may not show until you close the file.


In [ ]:
file1 = open("guvi.txt", "a")
file1.write("bbbbbbbbbb")
file1.close()

In [ ]:
os.remove("guvi.txt")

In [ ]:
#\n-->gives the new line
#\t--->gives one tab
file1= open("guvi2.txt", "w")
#Open file for writing
 
text = ["First Line \t", "Second Line\n", "Third Line"]
file1.writelines(text)
 
#Open file for reading
file1= open("guvi2.txt", "r")
print(file1.read())
file1.close()


First Line 	Second Line
Third Line


In [ ]:
#gives the current date and time.....
!date

Sat Feb 19 16:06:45 UTC 2022


In [ ]:
#one more topic in file handling seek(go through it from google)